[package]
name = "libomni"
description = "A utility library for Omni-forge and related programs"
authors = ["Omni-Forge <https://github.com/Omni-Forge>","Caznix <https://github.com/Caznix>"]
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"
[dependencies]
anyhow = "1.0.94"
regex = "1.11.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
